### ISSUE TITLE
database schema: typos and duplicates

### ISSUE THREAD

**Issue by schneefux** [vainglorygame/vainsocial.com#2]
`heroAssits` -> `heroAssists`

  * match:
    * `queue` and `gameMode` are the same - I'd assume this is an oversight from the API developers

  * match_participation:
    * kills, deaths, assist exist, but heroKills, heroDeaths, heroAssists too?

  * player
    * K/D/A is way more meaningful than K/D. Even D/A is more meaningful than K/D. vainglorygame/vainglorygame.github.io#1

**Comment by schneefux** [comment]
* there is no `afkCount` in the API data, there is only `wentAfk` (true or false).
  * on some tables, it is `krakenCaptures`, on others, `krakensCaptured`
  * `match_participation.rosterId` is an INT, but the API IDs are TEXT (look like hashes)

**Comment by kvahuja** [comment]
Queue may mean draft or blind.

Game modes may mean ranked or casual.
